version: '1'

networks:
  sae-network: # name of the network
    driver: bridge
    name: sae-network

services:
  sae-back-db: # name of the backend service
    container_name: sae-back-db
    env_file:
      - .env
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432" # postgres port (from .env file)
    environment:
      POSTGRES_USER: "${DB_USER}" # postgres username (from .env file)
      POSTGRES_PASSWORD: "${DB_PASSWORD}" # postgres password (from .env file)
      POSTGRES_DB: "${DB_NAME}" # postgres database name (from .env file)
    volumes:
      - "${DOCKER_DB_VOLUME_PATH}:/var/lib/postgresql/data"
    networks:
      - sae-network

  sae-backend:
    container_name: sae-backend
    env_file:
      - .env
    image: quarkus/sae-back-jvm
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://${DB_NAME}:${DB_PORT}/${DB_NAME}"
      QUARKUS_DATASOURCE_USERNAME: "${DB_USER}"
      QUARKUS_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: "${QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION}"
    ports:
      - "${QUARKUS_PORT}:8080" # backend port (from .env file)
    depends_on:
      - sae-back-db
    networks:
      - sae-network